#----------------------------------------------------------------------
#  @file   Makefile
#  @brief  photo driver Makefile
#  $Id: Makefile,v 1.2 2014/01/08 03:26:22 jedy Exp $
#  $Author: jedy $
#  $Revision: 1.2 $
#
#  Copyright (c) 2006 Terawins Inc. All rights reserved.
# 
#  @date   2013/10/02  hugo New file.
#----------------------------------------------------------------------
TOPDIR:=$(PROJ_NEZHA_DIR)
-include $(TOPDIR)/sysconfig

SOURCES = photo.c

LO_TARGET := photo.lo

include $(TOPDIR)/Rules.make

