#----------------------------------------------------------------------
#  @file   Makefile
#  @brief
#  $Id: Makefile,v 1.1 2014/03/14 12:11:36 ken Exp $
#  $Author: ken $
#  $Revision: 1.1 $
#
#  Copyright (c) 2006 Terawins Inc. All rights reserved.
#
#  @date   2007/02/27   jedy    New file.
#----------------------------------------------------------------------
TOPDIR := $(PROJ_NEZHA_DIR)
include .config

SOURCES= main.c page_mainmenu.c page_mainmenu2.c file_manip.c srv_evt_cmd.c lsf_manip.c
ALL_SUBOBJS= shell/shell.lo task/task.la OSD/OSD.la disp/disp.lo ring/ring.lo $(SYSLIB)

RESOURCE=t582_res.bin

DFU= app2.dfu

all: mkapp 

include $(TOPDIR)/Rules.make

clean: appclean

