#----------------------------------------------------------------------
#  @file   Makefile
#  @brief  Watchdog driver 
#  $Id: Makefile,v 1.1 2014/07/14 07:19:08 nick1516 Exp $
#  $Author: nick1516 $
#  $Revision: 1.1 $
#
#  Copyright (c) 2011 Terawins Inc. All rights reserved.
# 
#----------------------------------------------------------------------
TOPDIR:=$(PROJ_NEZHA_DIR)
-include $(TOPDIR)/sysconfig

SOURCES = gpioToiic.c

LO_TARGET := gpioToiic.lo

include $(TOPDIR)/Rules.make


