#----------------------------------------------------------------------
#  @file   Makefile
#  @brief  T582 demo for door phone
#  $Id: Makefile,v 1.1 2014/03/14 12:14:23 ken Exp $
#  $Author: ken $
#  $Revision: 1.1 $
#
#  Copyright (c) 2006 Terawins Inc. All rights reserved.
#
#  @date   2007/02/27   jedy    New file.
#----------------------------------------------------------------------
TOPDIR := $(PROJ_NEZHA_DIR)

-include ../.config

SOURCES = aumsg_service.c play_service.c pview_service.c rec_service.c snap_service.c auplay_service.c req_service.c snap_service.c slide_service.c md_service.c lsf_service.c
CFLAGS += -I..

include $(TOPDIR)/Rules.make



