TOPDIR:=$(PROJ_NEZHA_DIR)

SUPPRESS_CLEAN=1

-include $(TOPDIR)/Rules.make

clean:
	echo ">> <top>/codec_eng            skip cleaning <<<"

clean_sub:
	echo ">> <top>/codec_eng            skip cleaning <<<"

mklib:
	$(AR) cr codec_eng.la *.o
	$(AR) tv codec_eng.la

