#----------------------------------------------------------------------
#  @file   Makefile
#  @brief  sd drivers Makefile
#  $Id: Makefile,v 1.2 2014/01/08 03:26:22 jedy Exp $
#  $Author: jedy $
#  $Revision: 1.2 $
#
#  Copyright (c) 2006 Terawins Inc. All rights reserved.
# 
#  @date   2007/03/24  jedy New file.
#----------------------------------------------------------------------
TOPDIR:=$(PROJ_NEZHA_DIR)
-include $(TOPDIR)/sysconfig

SOURCES = sdraw.c sdinfo.c
LO_TARGET := sd.lo

include $(TOPDIR)/Rules.make
