#----------------------------------------------------------------------
#  @file   Makefile
#  @brief  Watchdog driver 
#  $Id: Makefile,v 1.1 2014/05/08 07:34:17 onejoe Exp $
#  $Author: onejoe $
#  $Revision: 1.1 $
#
#  Copyright (c) 2011 Terawins Inc. All rights reserved.
# 
#----------------------------------------------------------------------
TOPDIR:=$(PROJ_NEZHA_DIR)
-include $(TOPDIR)/sysconfig

SOURCES = iichost.c

LO_TARGET := iichost.lo

include $(TOPDIR)/Rules.make


