#----------------------------------------------------------------------
#  @file   Makefile
#  @brief  resource
#  $Id: Makefile,v 1.1 2014/07/25 10:18:23 nick1516 Exp $
#  $Author: nick1516 $
#  $Revision: 1.1 $
# 
#  Copyright (c) 2011   Terawins Inc. All rights reserved.
# 
#  @date   2011/11/24   ycs    New file.
#----------------------------------------------------------------------
TOPDIR:=$(PROJ_NEZHA_DIR)
-include ../.config

RINGS = t1.ring t2.ring t3.ring

LO_TARGET:=ring.lo

include $(TOPDIR)/Rules.make

