#----------------------------------------------------------------------
#  @file   Makefile
#  @brief  sd drivers Makefile
#  $Id: Makefile,v 1.5 2014/01/20 09:49:31 cnyu Exp $
#  $Author: cnyu $
#  $Revision: 1.5 $
#
#  Copyright (c) 2006 Terawins Inc. All rights reserved.
# 
#  @date   2007/03/24  jedy New file.
#----------------------------------------------------------------------
TOPDIR:=$(PROJ_NEZHA_DIR)
-include $(TOPDIR)/sysconfig

SOURCES = audio.T582B.c

LO_TARGET := audio.lo

include $(TOPDIR)/Rules.make

