#----------------------------------------------------------------------
#  @file   Makefile
#  @brief  app 
#  $Id: Makefile,v 1.1 2016/07/22 10:17:17 joec Exp $
#  $Author: joec $
#  $Revision: 1.1 $
#
#  Copyright (c) 2013 Terawins Inc. All rights reserved.
# 
#----------------------------------------------------------------------
TOPDIR:=$(PROJ_NEZHA_DIR)
-include $(TOPDIR)/sysconfig

SOURCES=display.c sysclock.c
LO_TARGET=disp.lo

include $(TOPDIR)/Rules.make

