/*
 *  @file   sysclock.c
 *  @brief  sysclock parameter according pixel clock
 *  $Id $
 *  $Author $
 *  $Revision: 1.1 $
 *
 *  Copyright (c) 2014 Terawins Inc. All rights reserved.
 *
 *  @date   2014/01/15  Tony    New file
 *
 */

/****************************************************************
 * following parameter is generated by green tool
 ****************************************************************/

const unsigned long VAL_SYSMGM_ALTFUNC_SEL  = 0x00143210;//(147230:無開RX ,  147210:無開RTS   , 143210 :開RTS)
const unsigned long VAL_SYSMGM_CLK_SEL      = 0x00000005;
const unsigned long VAL_SYSMGM_CLK_DIV      = 0x00521100;
const unsigned long VAL_SYSMGM_AHB_PLL      = 0x00001775;
const unsigned long VAL_SYS_CLK_SRC         = 30000000;

