#----------------------------------------------------------------------
#  @file   Makefile
#  @brief  fat2 subsystem Makefile
#  $Id: Makefile,v 1.6 2014/02/19 09:22:32 hugo Exp $
#  $Author: hugo $
#  $Revision: 1.6 $
#
#  Copyright (c) 2010 Terawins Inc. All rights reserved.
# 
#  @date   2010/02/08  New file.
#----------------------------------------------------------------------
TOPDIR:=$(PROJ_NEZHA_DIR)
-include $(TOPDIR)/sysconfig

SOURCES	= fatfs.c norfs.c norfs.deprecated.c

include $(TOPDIR)/Rules.make
