#----------------------------------------------------------------------
#  @file   Makefile
#  @brief  memory pool driver Makefile
#  $Id: Makefile,v 1.2 2014/01/08 03:26:22 jedy Exp $
#  $Author: jedy $
#  $Revision: 1.2 $
#
#  Copyright (c) 2013 Terawins Inc. All rights reserved.
# 
#  @date   2013/09/04  hugo New file.
#----------------------------------------------------------------------
TOPDIR:=$(PROJ_NEZHA_DIR)
-include $(TOPDIR)/sysconfig

SOURCES = mempool.c
LO_TARGET := mempool.lo

include $(TOPDIR)/Rules.make

