#define page_img_ctrl_view_process(x) 0
#define page_city_process(x) 0
#define page_city_img_ctrl_process(x) 0
#define page_city_live_process(x) 0
#define page_tower_process(x) 0
#define page_tower_img_ctrl_process(x) 0
#define page_tower_live_process(x) 0
#define page_sunflower_process(x) 0
#define page_sunflower_img_ctrl_process(x) 0
#define page_sunflower_live_process(x) 0
