#----------------------------------------------------------------------
#  @file   Makefile
#  @brief  T582 demo for door phone
#  $Id: Makefile,v 1.1 2015/07/15 09:53:57 kevin Exp $
#  $Author: kevin $
#  $Revision: 1.1 $
#
#  Copyright (c) 2006 Terawins Inc. All rights reserved.
#
#  @date   2007/02/27   jedy    New file.
#----------------------------------------------------------------------
TOPDIR=$(PROJ_NEZHA_DIR)
-include ../.config

SOURCES=$(ALL_C)
CFLAGS += -I..

include $(TOPDIR)/Rules.make

