#----------------------------------------------------------------------
#  @file   Makefile
#  @brief  Watchdog driver 
#  $Id: Makefile,v 1.2 2014/01/08 03:26:22 jedy Exp $
#  $Author: jedy $
#  $Revision: 1.2 $
#
#  Copyright (c) 2011 Terawins Inc. All rights reserved.
# 
#----------------------------------------------------------------------
TOPDIR:=$(PROJ_NEZHA_DIR)
-include $(TOPDIR)/sysconfig

SOURCES = watchdog.c

LO_TARGET := watchdog.lo

include $(TOPDIR)/Rules.make


