#----------------------------------------------------------------------
#  @file   Makefile
#  @brief  OmniVision Camera Chips drivers Makefile
#  $Id: Makefile,v 1.2 2014/01/08 03:26:22 jedy Exp $
#  $Author: jedy $
#  $Revision: 1.2 $
#
#  Copyright (c) 2010 Terawins Inc. All rights reserved.
# 
#  @date   2010/10/06  hugo New file.
#----------------------------------------------------------------------
TOPDIR:=$(PROJ_NEZHA_DIR)
-include $(TOPDIR)/sysconfig

SOURCES = spi.c tf040kfh01.c
LO_TARGET := spi.lo

include $(TOPDIR)/Rules.make


