#----------------------------------------------------------------------
#  @file   Makefile
#  @brief  nor flash drivers Makefile
#  $Id: Makefile,v 1.5 2014/01/27 01:56:36 hugo Exp $
#  $Author: hugo $
#  $Revision: 1.5 $
#
#  Copyright (c) 2006 Terawins Inc. All rights reserved.
# 
#  @date   2007/02/27  jedy New file.
#----------------------------------------------------------------------
TOPDIR:=$(PROJ_NEZHA_DIR)
-include $(TOPDIR)/sysconfig 
SOURCES = nor2.c
LO_TARGET := nor.lo

include $(TOPDIR)/Rules.make

