#----------------------------------------------------------------------
#  @file   Makefile
#  @brief  spi control function Makefile
#  $Id: Makefile,v 1.2 2014/01/08 03:26:22 jedy Exp $
#  $Author: jedy $
#  $Revision: 1.2 $
#
#  Copyright (c) 2012 Terawins Inc. All rights reserved.
# 
#  @date   2012/11/22  yc New file.
#----------------------------------------------------------------------
TOPDIR:=$(PROJ_NEZHA_DIR)
-include $(TOPDIR)/sysconfig

SOURCES = spirw.c 

LO_TARGET := spirw.lo

include $(TOPDIR)/Rules.make

