#----------------------------------------------------------------------
#  @file   Makefile
#  @brief  serail drivers Makefile
#  $Id: Makefile,v 1.3 2014/01/22 10:00:43 onejoe Exp $
#  $Author: onejoe $
#  $Revision: 1.3 $
#
#  Copyright (c) 2006 Terawins Inc. All rights reserved.
# 
#  @date   2007/02/27  jedy New file.
#----------------------------------------------------------------------
TOPDIR:=$(PROJ_NEZHA_DIR)
-include $(TOPDIR)/sysconfig

SOURCES = serial300.c serialafc.c
LO_TARGET := serial.lo

include $(TOPDIR)/Rules.make

