#----------------------------------------------------------------------
#  @file   Makefile
#  @brief  app 
#  $Id: Makefile,v 1.3 2014/01/17 10:40:45 kevin Exp $
#  $Author: kevin $
#  $Revision: 1.3 $
#
#  Copyright (c) 2013 Terawins Inc. All rights reserved.
# 
#----------------------------------------------------------------------
TOPDIR:=$(PROJ_NEZHA_DIR)
-include $(TOPDIR)/sysconfig

SOURCES=display.c sysclock.c
LO_TARGET=disp.lo

include $(TOPDIR)/Rules.make

