#----------------------------------------------------------------------
#  @file   Makefile
#  @brief  SD firmware upgrader
#  $Id: Makefile,v 1.4 2014/05/07 06:07:40 cnyu Exp $
#  $Author: cnyu $
#  $Revision: 1.4 $
#
#  Copyright (c) 2012 Terawins Inc. All rights reserved.
# 
#----------------------------------------------------------------------
TOPDIR:=$(PROJ_NEZHA_DIR)
-include $(TOPDIR)/sysconfig

SOURCES = ugprint.c upgrade.c upgrade_cache.c upgrade_sd.c upgrade_nor.c

LO_TARGET := upgrade.lo

include $(TOPDIR)/Rules.make


