#----------------------------------------------------------------------
#  @file   Makefile
#  @brief  
#  $Id: Makefile,v 1.2 2014/01/08 03:26:22 jedy Exp $
#  $Author: jedy $
#  $Revision: 1.2 $
#
#  Copyright (c) 2011 Terawins Inc. All rights reserved.
# 
#----------------------------------------------------------------------
TOPDIR:=$(PROJ_NEZHA_DIR)
-include $(TOPDIR)/sysconfig

SOURCES = ttl_hannstar_7.c ttl_hannstar_7_L_mode.c ttl_innolux_7_doorphone.c ttl_driver.c

LO_TARGET := ttl.lo

include $(TOPDIR)/Rules.make


