#----------------------------------------------------------------------
#  @file   Makefile
#  @brief  Audio AMP volume controled by PWM Makefile
#  $Id: Makefile,v 1.1 2014/02/27 07:53:12 kevin Exp $
#  $Author: kevin $
#  $Revision: 1.1 $
#
#  Copyright (c) 2010 Terawins Inc. All rights reserved.
# 
#  @date   2010/10/06  hugo New file.
#----------------------------------------------------------------------
TOPDIR:=$(PROJ_NEZHA_DIR)
#-include $(TOPDIR)/sysconfig

SOURCES = volume.c
LO_TARGET := volume.lo

include $(TOPDIR)/Rules.make


