#----------------------------------------------------------------------
#  @file   Makefile
#  @brief  T582 demo for door phone
#  $Id: Makefile,v 1.1 2014/07/25 10:14:23 nick1516 Exp $
#  $Author: nick1516 $
#  $Revision: 1.1 $
#
#  Copyright (c) 2006 Terawins Inc. All rights reserved.
#
#  @date   2007/02/27   jedy    New file.
#----------------------------------------------------------------------
TOPDIR=$(PROJ_NEZHA_DIR)
-include ../.config

SOURCES=$(ALL_C)
CFLAGS += -I..

include $(TOPDIR)/Rules.make

