#----------------------------------------------------------------------
#  @file   Makefile
#  @brief  osd2 drivers Makefile
#  $Id: Makefile,v 1.1 2014/01/10 06:08:17 onejoe Exp $
#  $Author: onejoe $
#  $Revision: 1.1 $
#
#  Copyright (c) 2012 Terawins Inc. All rights reserved.
# 
#  @date   2012/11/22 yc New file.
#----------------------------------------------------------------------
TOPDIR=$(PROJ_NEZHA_DIR)
-include $(TOPDIR)/sysconfig
SOURCES = mvfile.c
LO_TARGET := mvfile.lo

include $(TOPDIR)/Rules.make

